# -*- coding: utf-8 -*-
"""Bryan Cliff - 232_EntradaSaida_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GrxL3A0tywozXyj2MegikHZ-rb61qb9X

# Exercícios para construir programas com ENTRADA, PROCESSAMENTO e SAÍDA

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

# 1º passo - identificar a(s) entrada(s) - variável número
print('*** PROGRAMA PARA MULTIPLICAR UM NÚMERO POR DOIS***')
numero = int(input('Informe um valor......: '))

# 2º passo - identificar o processamento/cálculo
resultado = numero * 2

# 3º passo - apresentar a(s) variáveis que foram calculadas
print('A multiplicação é=',resultado)

"""### 2. Faça um programa que:
* receba três números inteiros
* calcule e mostre a soma desses números.

"""

# Digite aqui seu programa
# Entrada
numero1 = int(input('Digite o primeiro número: '))
numero2 = int(input('Digite o segundo número: '))
numero3 = int(input('Digite o terceiro número: '))
# Processamento/cálculo
soma_dos_numeros = numero1 + numero2 + numero3
# Saída
print("Resultado da soma:",soma_dos_numeros)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.     """

# Digite aqui seu programa
# Entrada
nota1 = int(input("Digite a primeira nota: "))
nota2 = int(input("Digite a segunda nota: "))
nota3 = int(input("Digite a terceira nota: "))

# Processamento/cálculo
todas_notas = nota1 + nota2 + nota3
média_nota = todas_notas / 3
# Saída
print("A média das notas é: ", média_nota)

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

# Digite aqui seu programa
salario = float(input("Digite seu salário aqui: "))
novoSalario = salario + (salario * 25 / 100)
print ("Seu salário com aumento é: ",novoSalario)

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

"""

# Digite aqui seu programa
salario = float (input("Digite seu salário aqui: "))
porcentagem = float (input("Percentual de seu aumento: "))
calculo_porcentagem = salario * porcentagem / 100
salario_atualizado = salario + (salario * porcentagem / 100)
print ("Seu aumento é de: ", calculo_porcentagem)
print ("Salário com aumento: ", salario_atualizado)

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e **paga imposto** de 7% também sobre o salário base."""

# Digite aqui seu programa
salario_base = float (input("Digite seu salário aqui: "))
gratificacao = salario_base * 5 / 100
imposto = salario_base * ( - 7 / 100)
salario_final = salario_base + gratificacao + imposto
print ("Salário a receber: ", salario_final)

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e **paga** imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

# Digite aqui seu programa
salario_base = float(input("Digite seu salário aqui: "))
perImposto = float(input("Percentual de imposto: "))
imposto = salario_base * perImposto / 100
salario_a_receber = salario_base + 50 - imposto
print ("Salário a receber: ", salario_a_receber)

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês.
    rendimento = deposito * taxa / 100
    total = deposito + rendimento
"""

# Digite aqui seu programa
valor_de_deposito = float(input("Digite aqui o valor de depósito: "))
taxa_de_juros = float(input("Digite aqui a taxa de juros: "))
rendimento = valor_de_deposito * taxa_de_juros / 100
valor_total = rendimento * 30
print("O valor do seu rendimento: ", rendimento)
print("Rendimento total de um mês: ", valor_total)

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2."""

# Digite aqui seu programa
base = float(input("Digite a base do triângulo aqui: "))
altura = float(input("Digite a altura do triângulo aqui: "))
area_triangulo =(base*altura) / 2
print("A área do triângulo é: ",area_triangulo)

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que:
    area = pi * raio²
    Como pi é um valor que conhecemos, então use a seguinte fórmula:
    area = 3.1415 * raio²
"""

# Digite aqui seu programa
raio = float(input("Digite aqui o raio do círculo: "))
pi = 3.1415
area_circulo = pi * (raio **2)
print ("A área do círculo é: ", area_circulo)

"""### 11. Faça um programa que receba um número, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitado

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** (½) (meio, ou 0.5)
      raiz_cubica = numero ** (⅓) (um terço, ou 0.33)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica


      raiz_quadrada = numero ** (1/2) ou
      raiz_quadrada = numero ** 0.5
"""

# Digite aqui seu programa
numero = float(input("Digite o número desejado aqui: "))
quadrado = numero * numero
cubo = numero ** 3
raiz_quadrada = numero ** (1/2)
raiz_cubica = numero ** (1/3)
print ("Número ao quadrado = ", quadrado)
print ("Número ao cubo = ", cubo)
print ("Número ao raiz quadrada = ", raiz_quadrada)
print ("Número ao raiz cúbica = ", raiz_cubica)

"""### 12. Faça um programa que receba dois números, calcule e mostre um elevado ao outro. Use os caracteres **

"""

# Digite aqui seu programa
numero1 = float(input("Digite o número que deseja elevar: "))
numero2 = float(input("Elevando o número a: "))
resultado = numero1 ** numero2
print("O número elevado é = ", resultado)

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

# Digite aqui seu programa
medida_pe = float(input("Digite aqui a medida em pés: "))
polegada = medida_pe * 12
jarda = medida_pe / 3
milha = jarda / 1760
print("Medida em polegadas: ", polegada)
print("Medida em jardas: ", jarda)
print("Medida em milhas: ", milha)

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade atual da pessoa;
* quantos anos ela terá em 2050.
"""

# Digite aqui seu programa
ano_nascimento = int(input("Digite aqui o ano de nascimento: "))
ano_atual = int(input("Ano em que você esta: "))
idade_atual = ano_atual - ano_nascimento
idade_2050 = 2050 - ano_nascimento
print ("Idade atual: ", idade_atual)
print ("Idade em 2050: ", idade_2050)

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_fabrica
        LEIA percentual_lucro_distribuidor
        LEIA percentual_imposto
        lucro_distribuidor = preco_fabrica * percentual_lucro_distribuidor / 100
        valor_imposto = preco_fabrica * percentual_imposto / 100
        preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
        ESCREVA lucro_distribuidor
        ESCREVA valor_imposto
        ESCREVA preco_final

"""

# Digite seu código aqui.
preco_fabrica = float(input("Digite aqui o preço de fabrica do veículo: "))
percentual_lucro_distribuidor = float(input("Digite aqui o percentual de lucro do distribuidor: "))
percentual_imposto = float(input("Digite aqui o percentual de imposto: "))
lucro_distribuidor = preco_fabrica * percentual_lucro_distribuidor / 100
valor_imposto = preco_fabrica * percentual_imposto / 100
preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
print ("O Lucro do disribuidor = ", lucro_distribuidor)
print ("Quantidade de imposto = ", valor_imposto)
print ("Preço final do veículo = ", preco_final)

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA qtde_horas_trabalhadas
      LEIA valor_salario_minimo
      valor_hora_trabalhada = valor_salario_minimo / 2
      valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
      imposto = valor_salario_bruto * 3 / 100
      valor_salario_liquido =  valor_salario_bruto - imposto
      ESCREVA valor_salario_liquido
"""

# Digite aqui seu programa
qtde_horas_trabalhadas = float(input("Digite aqui a quantidade de horas trabalhadas: "))
valor_salario_minimo = float(input("Digite aqui o valor do salário mínimo: "))
valor_hora_trabalhada = valor_salario_minimo / 2
valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
imposto = valor_salario_bruto * 3 / 100
valor_salario_liquido =  valor_salario_bruto - imposto
print("Salário a receber: ", valor_salario_liquido)

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      imposto_cheque1 = valor_cheque1 * 0.38 / 100
      saque1 = valor_cheque1 + imposto_cheque1
      imposto_cheque2 = valor_cheque2 * 0.38 / 100
      saque2 = valor_cheque2 + imposto_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo

"""

# Digite aqui seu programa
salario = float(input("Digite seu salário aqui: "))
valor_cheque1 = float(input("Digite o valor do primeiro cheque aqui: "))
valor_cheque2 = float(input("Digite o valor do segundo cheque aqui: "))
imposto_cheque1 = valor_cheque1 * 0.38 / 100
saque1 = valor_cheque1 + imposto_cheque1
imposto_cheque2 = valor_cheque2 * 0.38 / 100
saque2 = valor_cheque2 + imposto_cheque2
saldo = salario - saque1 - saque2
print("Saldo atual após cheques: ", saldo)

"""### 18. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      import math # carrega a biblioteca matemática
      radiano = angulo * math.pi / 180
      escada = altura / math.sin(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta, no cálculo, **math.sin(numero)**

**import math**

escada = altura / **math.sin**(numero)
"""

# import chama a biblioteca matemática e disponibiliza ao programa, várias
# funções prontas, basta usá-las quando necessário.
# Segue alguns exemplos:
print(f'Seno: {math.sin(90):.4f}\nCosseno: {math.cos(100):.4f}\nPotência: {math.pow(2,8):.4f}\nRaiz quadrada: {math.sqrt(24):.4f}')

# Digite aqui seu programa
import math # carrega biblioteca matemática
angulo = float(input("Digite aqui o angulo da escada (em graus): "))
altura = float(input("Digite aqui a altura da parede: "))
radiano = angulo * math.pi / 180
escada = altura / math.sin(radiano)
print(f"Tamanho da escada = {escada:.4f}")

"""###19. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_salario
      LEIA qtde_quilowatt
      valor_quilowatt = valor_salario / 5
      valor_em_reais = valor_quilowatt * qtde_quilowatt
      valor_descontado = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_descontado
      ESCREVA valor_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto

"""

# Digite aqui seu programa
valor_salario = float(input("Digite aqui o salário: "))
qtde_quilowatt = float(input("Diite aqui a quantidade de quilowatt consumidos: "))
valor_quilowatt = valor_salario / 5
valor_em_reais = valor_quilowatt * qtde_quilowatt
valor_descontado = valor_em_reais * 15 / 100
valor_com_desconto =  valor_em_reais - valor_descontado
print("Valor do quilowatt: ", valor_quilowatt)
print("Valor sem desconto: ",valor_em_reais)
print("Valor com desconto: ",valor_com_desconto)

"""### 20. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = round (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número mais próximo.


"""

# Digite aqui seu programa
numero = float(input("Digite seu número aqui: "))
parte_inteira = numero // 1
parte_fracionaria = numero - parte_inteira
numero_arredondado = round (numero)
print("Parte inteira: ", parte_inteira)
print("Parte fracionada: ", parte_fracionaria)
print("Número arredondado: ", numero_arredondado)

"""### 21. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao

"""

# Digite aqui seu programa
hora = float(input("Digite aqui a Hora no formato (4.30 = quatro horas e trinta minutos) para conversão em minutos: "))
h = hora // 1
minutos = hora - h
conversao = (h * 60) + (minutos * 100)
print("Hora convertida em minutos: ",conversao)

"""### 22. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

"""

1# Digite aqui seu programa
custo_teatro = float(input("Digite aqui o custo do teatro: "))
preco_convite = float(input("Digite aqui o preço do convite: "))
quant_vendidos = custo_teatro / preco_convite
resultado = round(quant_vendidos)
print("Quantidade mínima de convites a serem vendidos = ", resultado)