# -*- coding: utf-8 -*-
"""Bryan Cliff - 232_Est_Repeticao_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z9V25M4gpqA_As64uL4-lPbDjaBrgwvw

#ESTRUTURA DE REPETIÇÃO -> 1 a 13 - o restante fica para estudo
##Todos estes algoritmos/programas podem ser implementados com o comando **while** ou **for**. Para estudar, implemente cada exercício com as **duas** estruturas de repetição.

###1. Faça um algoritmo  que mostre 10 vezes a frase “Bem vindo a Fatec!”. Pode implementar com o comando while ou for.
"""

print('Exemplo do while.............')
# 1º passo - inicialização
contador = 1
# 2º passo - condição/critério de parada
while contador <= 10:
    print(f'{contador} Bem vindo a Fatec!')
    contador = contador + 1 # 3º passo - incremento

for contador in range(1,11): #range < 8
    print(f'{contador} Bem vindo a Fatec!')

"""###2. Faça um algoritmo que mostre o cumprimento ‘Olá ‘ para o nome de alguém (4 pessoas). Exemplo ‘Olá Mariana’. Pode implementar com o comando while ou for.

"""

pessoas = 0
while pessoas < 4:
    nome = input('Digite um nome: ')
    print(f'Olá {nome}')
    pessoas = pessoas + 1

for pessoas in range(4):
    nome = input('Digite um nome ')
    print(f'Olá {nome}')

"""###3. Faça um algoritmo que mostre os valores de 0 a 15. Pode implementar com o comando while ou for.

"""

for contador in range (16):
    print(contador)

"""###4. Faça um algoritmo que mostre os valores de 3 a 20. Pode implementar com o comando while ou for.

"""

for contador in range(3,21):
    print(contador)

"""###5. Faça um algoritmo que calcule e mostre a tabuada do 5. Pode implementar com o comando while ou for.

"""

numero = 5
for i in range(1,11):
    resultado = numero * i
    print(f'{numero} x {i} = {resultado}')

"""###6. Faça um algoritmo que receba a idade de 10 pessoas, calcule e exiba a quantidade de pessoas maiores de idade, sendo que a maioridade é obtida após completar 18 anos. Pode implementar com o comando while ou for.

"""

pessoas = 1
contador = 0
while pessoas <= 10:
    idade = int(input('Digite a idade aqui: '))
    if idade >= 18:
        contador = contador + 1
    pessoas = pessoas + 1
print(f'Quantidade de pessoas maiores de idade: {contador}')

# Digite seu código aqui com for

"""###7. Escreva um algoritmo que receba 23 números, calcule e exiba a quantidade de números pares e impares. Pode implementar com o comando while ou for.

"""

contador_pares = 0
contador_impares = 0
total_numeros = 23

while total_numeros > 0:
    numero = int(input("Digite um número: "))

    if numero % 2 == 0:
        contador_pares += 1
    else:
        contador_impares += 1

    total_numeros -= 1

print("Quantidade de números pares:", contador_pares)
print("Quantidade de números ímpares:", contador_impares)

"""###8. Faça um algoritmo que calcule e exiba o salário reajustado de dez funcionários de acordo com a seguinte regra (pode implementar com o comando while ou for):
## Salário até 300, reajuste de 50%;

##Salários maiores que 300, reajuste de 30%.



"""

salarios = []
for i in range(10):
    salario = float(input(f"Digite o salário do funcionário {i + 1}: "))
    salarios.append(salario)
salarios_reajustados = []
for salario in salarios:
    if salario <= 300:
        salario_reajustado = salario * 1.5
    else:
        salario_reajustado = salario * 1.3
    salarios_reajustados.append(salario_reajustado)
for i in range(10):
    print(f"Salário do funcionário {i + 1} reajustado: R${salarios_reajustados[i]:.2f}")

"""
###9. Faça um algoritmo que conheça 4 preços de produtos, some-os e mostre o resultado. Pode implementar com o comando while ou for.
"""

total = 0
for i in range(4):
    preco = float(input(f"Digite o preço do produto {i + 1}: "))
    total += preco
print("O total dos preços dos produtos é:", total)

"""###10. Faça um algoritmo que conheça 4 preços de produtos, calcule e mostre a média aritmética dos preços. Pode implementar com o comando while ou for.

"""

total = 0
contador = 0
while contador < 4:
    preco = float(input(f"Digite o preço do produto {contador + 1}: "))
    total += preco
    contador += 1
media = total / 4
print("A média dos preços dos produtos é:", media)

"""###11. Faça um algoritmo que calcule e informe a média de idades de 5 alunos. Pode implementar com o comando while ou for."""

soma_idades = 0
for i in range(5):
    idade = int(input(f"Digite a idade do aluno {i + 1}: "))
    soma_idades += idade
media_idades = soma_idades / 5
print("A média de idades dos alunos é:", media_idades)

"""###12. Faça um programa que receba a idade e a altura de 20 pessoas. Calcule e exiba a média das alturas das pessoas com mais de 20 anos.



"""

total_alturas = 0
total_pessoas_mais_de_20 = 0
for i in range(20):
    idade = int(input(f"Digite a idade da pessoa {i + 1}: "))
    altura = float(input(f"Digite a altura (em metros) da pessoa {i + 1}: "))
    if idade > 20:
        total_alturas += altura
        total_pessoas_mais_de_20 += 1
if total_pessoas_mais_de_20 > 0:
    media_alturas = total_alturas / total_pessoas_mais_de_20
    print("A média das alturas das pessoas com mais de 20 anos é:", media_alturas)
else:
    print("Nenhuma pessoa com mais de 20 anos inserida.")

"""###13. Faça um algoritmo que leia o preço de 20 TV, determine e apresente a média dos preços que possuem valor maior que R$ 1000. Pode implementar com o comando while ou for."""

total_precos = 0
contador_precos_maiores_que_1000 = 0
for i in range(20):
    preco = float(input(f"Digite o preço da TV {i + 1}: "))
    if preco > 1000:
        total_precos += preco
        contador_precos_maiores_que_1000 += 1
if contador_precos_maiores_que_1000 > 0:
    media_precos = total_precos / contador_precos_maiores_que_1000
    print("A média dos preços das TVs com valor maior que R$ 1000 é: R$", media_precos)
else:
    print("Nenhuma TV com valor maior que R$ 1000 inserida.")

"""###14. Faça um programa que receba a altura e nome  de 5 pessoas. Encontre e apresente a altura da pessoa mais alta e da mais baixa e seus respectivos nomes."""

altura_mais_alta = 0
nome_mais_alta = ""
altura_mais_baixa = float('inf')
nome_mais_baixa = ""
for i in range(5):
    nome = input(f"Digite o nome da pessoa {i + 1}: ")
    altura = float(input(f"Digite a altura (em metros) da pessoa {i + 1}: "))
    if altura > altura_mais_alta:
        altura_mais_alta = altura
        nome_mais_alta = nome
    if altura < altura_mais_baixa:
        altura_mais_baixa = altura
        nome_mais_baixa = nome
print(f"A pessoa mais alta é {nome_mais_alta} com {altura_mais_alta} metros de altura.")
print(f"A pessoa mais baixa é {nome_mais_baixa} com {altura_mais_baixa} metros de altura.")

"""###15. Faça um programa que receba dez valores inteiros, encontre e apresente o maior e o menor valor.


"""



"""###16. Os alunos do primeiro módulo farão a P1 da disciplina de Algoritmo. Crie um algoritmo que leia as 40 notas e RAs, encontre e apresente a maior, a menor e os respectivos RAs desses alunos."""



"""###17. Faça um programa que calcule e apresente as tabuadas do 3 ao 7. Este exercício utiliza DUAS estruturas de repetição."""

for numero_tabuada in range(3, 8):
    print(f"Tabuada do {numero_tabuada}:")
    for multiplicador in range(1, 11):
        resultado = numero_tabuada * multiplicador
        print(f"{numero_tabuada} x {multiplicador} = {resultado}")
    print()

"""###18. Faça um programa para o curso de ADS (6 módulos), cada sala tem 30 alunos, calcule e apresente os seguintes itens:
*  Quantidade de homens e mulheres de cada módulo;
*  Média de idades de cada módulo;
*  Quantidade de homens e mulheres do curso todo;
*  Média de idades do curso todo.

Observação: este exercício utiliza DUAS estruturas de repetição.
"""

