# -*- coding: utf-8 -*-
"""Bryan Cliff - 232_Est_Dec_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQcRzNHZDl9wXfmFpUdCZ1jBX-hDRYBD

#Lista de exercícios de ESTRUTURA de DECISÃO (estrutura condicional)
#Fazer do 1 ao 20, o restante fica para estudos

### 1.a) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%.
"""

salário = float(input('Digite o salário aqui: '))
if salário <= 500:
    novo = salário + (salário * 50 / 100)
    print(f'Novo salário: R$ {novo}')
else:
    novo = salário
    print(f'Novo salário: R$ {novo}')

"""###1.b) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%; Salários maiores que 500, reajuste de 30%."""

salario = float(input('Digite o salário aqui: '))
if salario <= 500:
    novo = salario + (salario * 50 / 100)
    print(f'Novo salário: R${novo:.2f}')
else:
    novo2 = salario + (salario * 30/100)
    print(f'Novo salário: R${novo2:.2f}')

"""###1.c) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%; Salários maiores que 500 e até 1000, reajuste de 30%; Salários acima de 1000, reajuste de 10%."""

salario = float(input("Cadastre um salario: "))
if salario <= 500:
    novo = salario + (salario*50/100)
    print(f'Novo salário: R${novo:.2f}')
elif salario >= 501 and salario <= 1000:
    novo1 = salario + (salario*30/100)
    print(f'Novo salário: R${novo1:.2f}')
else:
    novo2 = salario + (salario*10/100)
    print(f'Novo salário: R${novo2:.2f}')

"""###2. Faça um algoritmo que leia o nome e a idade de uma pessoa, verifique se a idade de uma pessoa é menor ou maior de idade. Considera-se maior de idade uma pessoa com 18 anos ou mais. Como saída o algoritmo deve informar o nome e a idade da pessoa e depois uma mensagem se ela é ou não maior de idade.

"""

nome = str(input('Insira aqui seu nome: '))
idade = int(input('Digite sua idade aqui: '))
if idade <= 17:
    print(f'Olá {nome}, você é menor de idade pois tem {idade} anos')
elif idade >= 18:
    print(f'Olá {nome}, você é maior de idade pois tem {idade} anos')

"""###3.a) Faça um algoritmo que leia duas notas de um aluno, calcule a média e verifique, apresentando, se está aprovado ou reprovado."""

nota1 = float(input('Digite aqui a sua primeira nota: '))
nota2 = float(input('Digite aqui a sua segunda nota: '))
media = (nota1 + nota2) /2
if media <= 4.9:
    print(f'Sua média final é {media}, portanto você está REPROVADO por não atingir o mínimo de 5 pontos.')
elif media >= 5:
    print(f'Sua média final é {media}, portanto você está APROVADO poís sua nota ultrapasou os 5 pontos.')

"""###3.b) Faça um algoritmo que calcule e apresente o que foi requerido no exercício 3.a) e também avalie a condição de aprovar/reprovar, apenas quando o aluno tem frequencia acima de 75%, este valor deve ser lido."""

nota1 = float(input('Digite aqui a sua primeira nota: '))
nota2 = float(input('Digite aqui a sua segunda nota: '))
frequencia = float(input('Digite aqui o seu percentual de presença: '))
media = (nota1 + nota2) /2
if media <= 4.9:
    print(f'Sua média final é {media:.1f}, portanto você está REPROVADO por não atingir o mínimo de 5 pontos.')
elif media >= 5 and frequencia >= 75:
    print(f'Sua média final e frenquência atingiram os requisitos mínimos, portanto você está APROVADO.')
elif media >= 5 and frequencia <= 74.9:
    print(f'Sua frequência é de {frequencia:.0f}%, portanto você está REPROVADO poís não foi atingida a frequência mínima de 75%.')

"""###4. Faça um algoritmo que leia o gênero de uma pessoa. Se for digitado M ou F, apresentar 'Gênero válido!'. Caso contrário, 'Gênero inválido!'."""

genero = str(input('Digite seu gênero aqui com (M) masculino ou (F) feminino: '))
if genero == 'M' or genero == 'F':
    print(f'Gênero válido!')
else:
    print(f'Gênero inválido!')

"""###5. Tendo como dados de entrada a altura e o gênero (M/F) de uma pessoa (M-masculino ou F-feminino), construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
masculino: (72.7 * altura) - 58;

feminino: (62.1 * altura) - 44.7


"""

altura = float(input('digite a altura desejada aqui: '))
genero = str(input('digite o seu gênero aqui com (M) masculino ou (F) feminino: '))
peso_m = (72.7 * altura) - 58
peso_f = (62.1 * altura) - 44.7
if genero == 'M':
    print(f'Seu peso ideial é {peso_m:.2f} kg.')
elif genero == 'F':
    print(f'Seu peso ideal é {peso_f:.2f} kg.')
else:
    print(f'Você digitou seu gênero errado.')

"""###6. Faça um algoritmo que leia dois números inteiros e mostre o resultado da **diferença** do maior valor pelo menor."""

numero1 = int(input('digite aqui o primeiro número: '))
numero2 = int(input('digite aqui o segundo número: '))
if numero1 > numero2:
    print(numero1 - numero2)
else:
    print(numero2 - numero1)

"""###7. Uma faculdade faz o pagamento de seus professores por hora/aula. Faça um algoritmo que receba o nível e a quantidade de hora/aula, calcule e exiba o salário de um professor e a frase a seguira tabela abaixo:
Professor Nível 1 - 11,00 reais por hora/aula, salário: ...

Professor Nível 2 - 15,00 reais por hora/aula, salário: ...

Professor Nível 3 - 19,00 reais por hora/aula, salário: ...
"""

nivel = str(input('Digite aqui o nível de professor (1, 2 ou 3): '))
quantidade = float(input('Digite aqui a quantidade de horas trabalhadas: '))
nivel1 = quantidade * 11
nivel2 = quantidade * 15
nivel3 = quantidade * 19
if nivel == '1':
    print(f'Olá professor Nível 1, esse é o seu salário a receber: {nivel1:.2f}R$')
elif nivel == '2':
    print(f'Olá professor Nível 2, esse é o seu salário a receber: {nivel2:.2f}R$')
elif nivel == '3':
    print(f'Olá professor Nível 3, esse é o seu salário a receber: {nivel3:.2f}R$')

"""###8. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se este número é par ou ímpar e se é positivo ou negativo.

"""

numero = int(input('Digite aqui um número inteiro aqui: '))
if numero % 2 == 0:
    print(f'O número {numero} é par.')
else:
    print(f'O número {numero} é impar.')
if numero > 0:
    print(f'O número {numero} é positivo.')
elif numero < 0:
    print(f'O número {numero} é negativo.')
else:
    print(f'O número {numero} é zero')

"""###9. Num determinado Estado, para transferências de veículos, o DETRAN cobra uma taxa de 1% para carros fabricados antes de 1990 e uma taxa de 1.5% para os fabricados de 1990 em diante, taxa esta incidindo sobre o valor de tabela do carro. Faça um algoritmo que leia o ano e o preço do carro, calcule e apresente o imposto a ser pago."""

ano_taxa = int(input('Didite aqui o ano do carro: '))
valor_carro = float(input('Digite aqui o valor do carro: '))
taxa_menos_1990 = valor_carro + (valor_carro * 1/100)
taxaaa_menos_1990 = (valor_carro * 1/100)
taxa_igual_mais_1990 =  valor_carro + (valor_carro * 1.5/100)
taxaaa_igual_mais_1990 = (valor_carro * 1.5/100)
if ano_taxa <= 1989:
    print(f'O carro de ano {ano_taxa} custa {taxa_menos_1990:.2f}R$, sendo desse valor {taxaaa_menos_1990:.2f}R$ de imposto.')
elif ano_taxa >= 1990:
    print(f'O carro de ano {ano_taxa} custa {taxa_igual_mais_1990:.2f}R$, sendo desse valor {taxaaa_igual_mais_1990:.2f}R$ de imposto.')

"""###10. Elabore um algoritmo que informando a idade de um nadador o mesmo terá condições de classificar em uma das seguintes categorias:
infantil = 5 - 10 anos;

juvenil = 11-17 anos;

adulto = maiores de 18 anos.


"""

idade_nadador = int(input('Digite aqui a idade do nadador: '))
if idade_nadador >= 5 and idade_nadador <= 10:
    print(f'Você terá condições de se classificar na categoria infantil por ter {idade_nadador} anos.')
elif idade_nadador >= 11 and idade_nadador <= 17:
    print(f'Você terá condições de se classificar na categoria juvenil por ter {idade_nadador} anos.')
elif idade_nadador >= 18:
    print(f'Você terá condições de se classificar na categoria adulto por ter {idade_nadador} anos.')
else:
    print(f'Você não podera se classificar em nenhuma categoria por ter menos de 4 anos.')

"""###11. Um banco concederá um crédito especial aos seus clientes, variável com o saldo médio no último ano. Faça um algoritmo que leia o saldo médio de um cliente e calcule o valor do crédito de acordo com a tabela a seguir. Mostre uma mensagem informando o saldo médio e o valor do crédito.
        Saldo médio
        * de 0 a 200 nenhum crédito
        * de 201 a  400 20% do valor do saldo médio
        * de 401 a  600 30% do valor do saldo médio
        * acima de 601 40% do valor do saldo médio

"""

saldo_medio = float(input('Digite aqui qual foi o seu saldo médio no último ano: '))
vinteporcento = (saldo_medio * 20/100)
trintaporcento = (saldo_medio * 30/100)
quarentaporcento = (saldo_medio * 40/100)
if saldo_medio <= 200:
    print(f'Você não tem nenhum saldo disponível')
elif saldo_medio >= 201 and saldo_medio <= 400:
    print(f'Você tem {saldo_medio:.2f} reais de saldo médio e {vinteporcento:.2f} reais de crédito.')
elif saldo_medio >= 401 and saldo_medio <= 600:
    print(f'Você tem {saldo_medio:.2f} reais de saldo médio e {trintaporcento:.2f} reais de crédito.')
else:
    print(f'Você tem {saldo_medio:.2f} reais de saldo médio e {quarentaporcento:.2f} reais de crédito.')

"""###12. A Organização Mundial de Saúde usa a seguinte tabela para determinar a condição de um adulto, para isso desenvolva um algoritmo para calcular o Índice de Massa Corporal (IMC) e apresenta-lo, dado pela fórmula:
    IMC = peso / (altura)2   (o número 2 significa, elevado ao quadrado)

CONDIÇÃO |  IMC em adultos |
 ---|---
Abaixo do peso  |	Abaixo de 18.5  |
No peso normal	|	Entre 18.5 e 25|
Acima do peso	|	Entre 25.1 e 30|
Obeso		    |	Acima de 30|
"""

peso = float(input('Digite aqui o seu peso: '))
altura = float(input('Digite aqui a sua altura (formato 1.74): '))
imc = peso / (altura ** 2)
if imc < 18.4:
    print(f'Você está abaixo do peso.')
elif imc >= 18.5 and imc <= 25:
    print('Você está no seu peso normal.')
elif imc >= 25.1 and imc <= 30:
    print('Você está acima do peso.')
else:
    print('Você está em estado de obesidade.')

"""###13. A nota final de um estudante é calculada a partir de três notas atribuídas, respectivamente, a um trabalho de laboratório, a uma avaliação semestral e a um exame final. A média das três notas mencionadas obedece aos pesos a seguir:

 NOTA |  PESO |
 ---|---
Trabalho de laboratório  |   2   |
Avaliação semestral      |   3   |
Exame final              |   5   |

### Faça um programa que receba as três notas, calcule e mostre a média ponderada e o conceito que segue a tabela

MÉDIA PONDERADA    | CONCEITO|
---|---
8,0 <= média <= 10  |    A
7,0 <= média < 8,0  |    B
6,0 <= média < 7,0  |    C
5,0 <= média < 6,0  |    D
 0,0 <= média < 5,0  |    E
       
media_ponderada = (nota_traballho * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10


"""

laboratorio = float(input('Digite aqui a nota do Trabalho de Laboratório: '))
semestral = float(input('Digite aqui a nota da Avaliação Semestral: '))
final = float(input('Digite aqui a nota do Exame Final: '))
media_ponderada = (laboratorio * 2 + semestral * 3 + final * 5) / 10
if media_ponderada >= 8 and media_ponderada <= 10:
    print(f'A sua média ponderada é {media_ponderada}, sendo equivalente ao conceito A.')
elif media_ponderada >= 7 and media_ponderada <= 8:
    print(f'A sua média ponderada de {media_ponderada}, sendo equivalente ao conceito B.')
elif media_ponderada >= 6 and media_ponderada <= 7:
    print(f'A sua média ponderada de {media_ponderada}, sendo equivalente ao conceito C.')
elif media_ponderada >= 5 and media_ponderada <= 6:
    print(f'A sua média ponderada de {media_ponderada}, sendo equivalente ao conceito D.')
elif media_ponderada >= 0 and media_ponderada <= 5:
    print(f'A sua média ponderada de {media_ponderada}, sendo equivalente ao conceito E.')

"""### 14. Faça um programa que receba três notas de um aluno, calcule e mostre a média aritmética e a mensagem constante na tabela a seguir. Aos alunos que ficaram para exame, calcule e mostre a nota que deverão tirar para serem aprovados, considerando que a média exigida é 6,0.

**Observação**: Esta condição de reprovado e exame, não representa a realidade da faculdade.

MÉDIA ARITMÉTICA | MENSAGEM
    ---|---
    0 <= média < 3 |Reprovado
    3 <= média < 6|Exame
    6 <= média <= 10|Aprovado

```
SE media >= 3 E media < 6
    ESCREVA “Exame”
    nota_exame = 12 - media
    ESCREVA “Você deve tirar a nota”, nota_exame, “para ser aprovado.”

"""

nota1 = float(input('Digite sua primeira nota aqui: '))
nota2 = float(input('Digite sua segunda nota aqui: '))
nota3 = float(input('Digite sua terceira nota aqui: '))
media = (nota1 + nota2 + nota3) / 3
nota_exame = 12 - media
if media <= 3:
    print('Você foi reprovado.')
elif media >= 3.1 and media < 5.9:
    print(f'Você foi para exame e deve tirar a nota, {nota_exame:.2f}, para ser aprovado.')
elif media >= 6 and media <= 10:
    print('Você foi provado.')

"""### 15. Faça um programa que receba dois números e mostre o maior.

"""

numero1 = float(input('Digite aqui o primeiro número: '))
numero2 = float(input('digite aqui o segundo número: '))
if numero1 > numero2:
    print(f'O maior número é {numero1}')
else:
    print(f'Os maior número é {numero2}')

"""### 16. Faça um programa que receba três números e mostre-os em ordem crescente. Suponha que o usuário digitará três números diferentes.

```
SE numero1 < numero2 E numero1 < numero3
    SE numero2 < numero3
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero2,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero3,“-”,numero2
SE numero2 < numero1 E numero2 < numero3
    SE numero1 < numero3
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero1,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero3,“-”,numero1
SE numero3 < numero1 E numero3 < num2
    SE numero1 < numero2
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero1,“-”,numero2
    SENÃO
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero2,“-”,numero1
  ```
"""

numero1 = float(input('Digite aqui o primeiro número: '))
numero2 = float(input('Digite aqui o segundo número: '))
numero3 = float(input('Digite aqui o terceiro número: '))
if numero1 < numero2 < numero3:
    print(f'A ordem dos números em crescente é {numero1}, {numero2} e {numero3}.')
elif numero1 < numero3 < numero2:
    print(f'A ordem dos números em crescente é {numero1}, {numero3} e {numero2}.')
elif numero2 < numero1 < numero3:
    print(f'A ordem dos números em crescente é {numero2}, {numero1} e {numero3}.')
elif numero2 < numero3 < numero1:
    print(f'A ordem dos números em crescente é {numero2}, {numero3} e {numero1}.')
elif numero3 < numero2 < numero1:
    print(f'A ordem dos números em crescente é {numero3}, {numero2} e {numero1}.')
elif numero3 < numero1 < numero2:
    print(f'A ordem dos números em crescente é {numero3}, {numero1} e {numero2}.')

"""### 17. Faça um programa que receba três números obrigatoriamente em ordem crescente e um quarto número que não siga essa regra. Mostre, em seguida, os quatro números em ordem decrescente. Suponha que o usuário digitará quatro números diferentes.

```code
SE numero4 > numero3
    ESCREVA “A ordem decrescente é: “,numero4,“-”,numero3,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero2 E numero4 < numero3
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero4,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero1 E numero4 < numero2
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero4, “-”,numero1
SENÃO SE numero4 < numero1
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero1,“-”,numero4
```
"""

numero1 = float(input('Digite aqui o primeiro número: '))
numero2 = float(input('Digite aqui o segundo número: '))
numero3 = float(input('Digite aqui o terceiro número: '))
numero4 = float(input('Digite aqui o quarto número: '))
if numero4 > numero3:
    print(f'A ordem decrescente é {numero4}, {numero3}, {numero2} e {numero1}.')
elif numero4 > numero2 and numero4 < numero3:
    print(f'A ordem decrescente é {numero3}, {numero4}, {numero2} e {numero1}.')
elif numero4 > numero1 and numero4 < numero2:
    print(f'A ordem decrescente é {numero3}, {numero2}, {numero4} e {numero1}.')
elif numero4 < numero1:
    print(f'A ordem decrescente é {numero3}, {numero2}, {numero1} e {numero4}.')

"""### 18. Faça um programa que receba quatro valores: I, A, B e C. Desses valores, I é inteiro e positivo, A, B e C são reais. Escreva os números A, B e C obedecendo à tabela a seguir.

*Suponha que o valor digitado para I seja sempre um valor válido, ou seja, 1, 2 ou 3, e que os números digitados sejam diferentes um do outro.*

  |VALOR DE I | FORMA A ESCREVER|
  |---|---|
  |1                  |A, B e C em ordem crescente.|
  |2                  |A, B e C em ordem decrescente|
  |3                  |O maior fica entre os outros dois números.|

  ```code
SE I == 1
    SE A<B E A<C
        SE B<C
            ESCREVA “A ordem crescente dos números é:”,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é:”,A,” -”,C,”-”,B
    SE B<A E B<C
        SE A<C
            ESCREVA “A ordem crescente dos números é:”,B,”-”,A,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,B,”-”,C,”-”,A
    SE C<A E C<B
        SE A<B
            ESCREVA “A ordem crescente dos números é: “,C,”-”,A,”-”,B
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,C,”-”,B,”-”,A
SE I == 2
    SE A>B E A>C
        SE B>C
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,C,”-”,B
    SE B>A E B>C
        SE A>C
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,A,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,C,”-”,A
    SE C>A E C>B
        SE A>B
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,A,”-”,B
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,B,”-”,A
SE I == 3
    SE A>B E A>C
        ESCREVA “A ordem desejada é: “,B,”-”,A,”-”,C
    SE B>A E B>C
        ESCREVA “A ordem desejada é: “,A,”-”,B,”-”,C
    SE C>A E C>B
        ESCREVA “A ordem desejada é: “,A,”-”,C,”-”,B
```
"""

I = int(input('Digite aqui (1) para ordem crescente, (2) ordem decrescente ou (3) para exibir o maior número ao centro: '))
A = float(input('Digite aqui o primeiro número: '))
B = float(input('Digite aqui o segundo número: '))
C = float(input('Digite aqui o terceiro número: '))

if I == 1:
    if A < B < C:
        print('A ordem crescente dos números é: ',A,', ',B,' e ',C,'.')
    elif A < C < B:
        print(f'A ordem crescente dos números é: {A}, {C} e {B}.')
    elif B < A < C:
        print(f'A ordem crescente dos números é: {B}, {A} e {C}.')
    elif B < C < A:
        print(f'A ordem crescente dos números é: {B}, {C} e {A}.')
    elif C < A < B:
        print(f'A ordem crescente dos números é: {C}, {A} e {B}.')
    elif C < B < A:
        print(f'A ordem crescente dos números é: {C}, {B} e {A}.')

elif I == 2:
    if A > B > C:
        print(f'A ordem decrescente dos números é: {A}, {B} e {C}.')
    elif A > C > B:
        print(f'A ordem decrescente dos números é: {A}, {C} e {B}.')
    elif B > A > C:
        print(f'A ordem decrescente dos números é: {B}, {A} e {C}.')
    elif B > C > A:
        print(f'A ordem decrescente dos números é: {B}, {C} e {A}.')
    elif C > A > B:
        print(f'A ordem decrescente dos números é: {C}, {A} e {B}.')
    elif C > B > A:
        print(f'A ordem decrescente dos números é: {C}, {B} e {A}.')

elif I == 3:
    if A > B > C:
        print(f'Ordem com o maior número ao centro é: {B}, {A} e {C}.')
    elif A > C > B:
        print(f'Ordem com o maior número ao centro é: {C}, {A} e {B}.')
    elif B > A > C:
        print(f'Ordem com o maior número ao centro é: {A}, {B} e {C}.')
    elif B > C > A:
        print(f'Ordem com o maior número ao centro é: {C}, {B} e {A}.')
    elif C > A > B:
        print(f'Ordem com o maior número ao centro é: {A}, {C} e {B}.')
    elif C > B > A:
        print(f'Ordem com o maior número ao centro é: {B}, {C} e {A}.')

"""### 19. Faça um programa que mostre o menu de opções a seguir, receba a opção do usuário, número 1 para a escolha da soma, ou número 2 para a raiz quadrada, também receba os dados necessários para executar cada operação.

    Menu de opções:
    1. Somar dois números.
    2. Raiz quadrada de um número.

Observação: raiz = numero ** (1/2), ou
import math
raiz = math.sqrt(numero), assim como foi programado no exercício 18, da lista anterior.
      
"""

print("Menu de opçoes")
print("1. Somar dois numeros.")
print("2. Raiz quadrada de um numero.")
menu = int(input("Digite a opção desejada:"))
numero1 = float(input('Digite o número aqui: '))
if menu == 1:
 numero2 = float(input('Digite o segundo número aqui: '))
 soma = numero1 + numero2
 print(f'A soma dos números é {soma}.')
elif menu == 2:
 raiz = numero1 ** 0.5
 print(f'A raiz do número requirido é {raiz}')

"""### 20. Faça um programa que mostre a data e a hora do sistema nos seguintes formatos: **dia/mês/ano – mês por extenso e hora:minuto**.

**Observação: ***from*** carrega um módulo/biblioteca da linguagem Python e o ***import*** é usado para informar qual objeto desta biblioteca queremos importar/carregar no nosso programa. Se colocar apenas import será carregado tudo que tem dentro da biblioteca.**

    from datetime import datetime
    #Este comando obtem a data e hora de hoje de algum país onde esta o servidor que executa nosso programa feito no Collab, em Python.
    #Quando eu testei, o servidor era do fuso horário de Dakar-Senegal
    hoje = datetime.now()
    print ('Ano atual.:',hoje.year)
    print ('Mês.......:',hoje.month)
    print ('Dia.......:',hoje.day)
    print ('Hora......:',hoje.hour)
    print ('Minuto....:',hoje.minute)
    print ('Segundos..:',hoje.second)
"""

from datetime import datetime
hoje = datetime.now()
print ('Ano atual.:',hoje.year)
print ('Mês.......:',hoje.month)
print ('Dia.......:',hoje.day)
print ('Hora......:',hoje.hour)
print ('Minuto....:',hoje.minute)
print ('Segundos..:',hoje.second)
if hoje.month == 1:
    print(hoje.day,'/Janeiro/',hoje.year)
#...............................................
# Dê continuidade a programação daqui pra frente
elif hoje.month == 2:
    print(hoje.day, '/Fevereiro/', hoje.year)
elif hoje.month == 3:
    print(hoje.day, '/Março/', hoje.year)
elif hoje.month == 4:
    print(hoje.day, '/Abril/', hoje.year)
elif hoje.month == 5:
    print(hoje.day, '/Maio/', hoje.year)
elif hoje.month == 6:
    print(hoje.day, '/Junho/', hoje.year)
elif hoje.month == 7:
    print(hoje.day, '/Julho/', hoje.year)
elif hoje.month == 8:
    print(hoje.day, '/Agosto/', hoje.year)
elif hoje.month == 9:
    print(hoje.day, '/Setembro/', hoje.year)
elif hoje.month == 10:
    print(hoje.day, '/Outubro/', hoje.year)
elif hoje.month == 11:
    print(hoje.day, '/Novembro/', hoje.year)
elif hoje.month == 12:
    print(hoje.day, '/Dezembro/', hoje.year)

# DICA-curiosidade, o trecho de código a
# seguir, mostra como trocar o fuso
# horário para o país que deseja, no caso Brasil
###################################################
# datetime nome do arquivo onde contém as
# classes/funções (datetime, timezone, timedelta)
# que eu desejo usar, neste exemplo
# datetime, timezone, timedelta
###################################################
from datetime import datetime, timezone, timedelta

data_e_hora_atuais = datetime.now()
fuso_horario = timezone(timedelta(hours=-3))
print('UTC - Tempo Universal Coordenado:', fuso_horario)
data_e_hora_SP = data_e_hora_atuais.astimezone(fuso_horario)
data_e_hora_SP_em_texto = data_e_hora_SP.strftime('%d/%m/%Y %H:%M')
print('Data e horário de São Paulo:',data_e_hora_SP_em_texto)

"""### 21. Faça um programa que determine a data cronologicamente maior entre duas datas fornecidas pelo usuário. Cada data deve ser composta por três valores inteiros, em que o primeiro representa o dia, o segundo, o mês e o terceiro, o ano.

  ```code
  SE ano1 > ano2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE ano2>ano1
      ESCREVA “A maior data é: “,dia2,”-”,mes2,”-”,ano2
  SENÃO SE mes1>mes2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE mes2>mes1
      ESCREVA “A maior data é: “,dia2, “-”,mes2,”-”,ano2
  SENÃO SE dia1>dia2
      ESCREVA “A maior data é: “-”,dia1,”-”,mia1,” -”,ano1
  SENÃO SE dia2>dia1
      ESCREVA “A maior data é: “,dia2,” -”,mes2,”-”,ano2
  SENÃO
      ESCREVA “As datas são iguais!”
  ```
"""

# Digite seu código aqui

"""### 22. Faça um programa que receba a hora do início de um jogo e a hora do término (cada hora é composta por duas variáveis inteiras: hora e minuto). Calcule e mostre a duração do jogo (horas e minutos), sabendo que o tempo máximo de duração do jogo é de 24 horas e que ele pode começar em um dia e terminar no dia seguinte.
    SE min_inicial > min_f
        min_final = min_final + 60
        hora_final = hora_final – 1
    SE hora_inicial > hora_final
        hora_final = hora_final + 24
    minuto_duracao = min_final - min_inicial
    hora_duracao = hora_final - hora_inicial
"""

# Digite seu código aqui

"""### 23. Faça um programa que receba o código correspondente ao cargo de um funcionário e seu salário atual e mostre o cargo, o valor do aumento e seu novo salário. Os cargos estão na tabela a seguir.

  |CÓDIGO|CARGO|PERCENTUAL|
  |---|---|---|
  |1|Escriturário|50%|
  |2|Secretário|35%|
  |3|Caixa|20%|
  |4|Gerente|10%|
  |5|Diretor|Não tem aumento|

```code
SE cargo == 1
    ESCREVA “O cargo é Escriturário”
    aumento = salario * 50 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 2
    ESCREVA “O cargo é Secretário”
    aumento = salario * 35 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal]
SENÃO SE cargo == 3
    ESCREVA “O cargo é Caixa”
    aumento = salario * 20 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “,novo_sal
SENÃO SE cargo == 4
    ESCREVA “O cargo é Gerente”
    aumento = salario * 10 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 5
    ESCREVA “O cargo é Diretor”
    aumento = salario * 0 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
```
"""

# Digite seu código aqui

"""### 24. Faça um programa que apresente o menu a seguir, permita ao usuário escolher a opção desejada, receba os dados necessários para executar a operação e mostre o resultado. Verifique a possibilidade de opção inválida e não se preocupe com restrições, como salário negativo.

    Menu de opções
    1. Imposto
    2. Novo salário
    3. Classificação
    Digite a opção desejada:

*Na opção 1: receber o salário de um funcionário, calcular e mostrar o valor do imposto usando as regras a seguir.*

  |SALÁRIO|PERCENTUAL DO IMPOSTO|
  |---|---|
  |Menor que  500,00|5%|
  |De  500,00 (inclusive) a  850,00 (inclusive)|10%|
  |Acima de  850,00|15%|

*Na opção 2: receber o salário de um funcionário, calcular e mostrar o valor do novo salário, usando as regras a seguir.*

  |SALÁRIO|AUMENTO|
  |---|---|
  |Maior que  1.500,00| 25,00|
  |De  750,01 a  1.500,00 (inclusive)| 50,00|
  |De  450,00 (inclusive) a  750,00| 75,00|
  |Menor que  450,00| 100,00|

*Na opção 3: receber o salário de um funcionário e mostrar sua classificação usando a tabela a seguir.*

|SALÁRIO|CLASSIFICAÇÃO|
|---|---|
|Até  700,00 (inclusive)|Mal remunerado|
|Maiores que  700,00|Bem remunerado|

"""

# Digite seu código aqui

"""###25. Faça um programa que receba o salário inicial de um funcionário, calcule e mostre o novo salário, acrescido de bonificação e de auxílio escola.

|SALÁRIO|BONIFICAÇÃO|
|---|---|
|Até  500,00|5% do salário|
|Entre  500,01 e 1.200,00|12% do salário|
|Acima de  1.200,00|Sem bonificação|
>
|SALÁRIO|AUXÍLIO ESCOLA|
|---|---|
|Até  600,00| 150,00|
|Acima de  600,00| 100,00|

novo_salario = salario + bonificacao + auxílio escola
"""

# Digite seu código aqui

"""### 26. Faça um programa que receba o valor do salário mínimo, o número de horas trabalhadas, o número de dependentes do funcionário e a quantidade de horas extras trabalhadas. Calcule e mostre o salário a receber do funcionário de acordo com as regras a seguir:

  * O valor da hora trabalhada é igual a 1/5 do salário mínimo.
  * O salário do mês é igual ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
  * Para cada dependente, acrescentar  32,00.
  * Para cada hora extra trabalhada, calcular o valor da hora * trabalhada acrescida de 50%.
  * O salário bruto é igual ao salário do mês mais o valor dos dependentes mais o valor das horas extras.
  * Calcular o valor do impostoosto de renda retido na fonte de acordo com a tabela a seguir:

|IRFF|SALÁRIO BRUTO|
|---|---|
|Isento|Inferior a  200,00|
|10%|De  200,00 até 500,00|
|20%|Superior a  500,00|

  * O salário líquido é igual ao salário bruto menos IRRF.
  * A gratificação é de acordo com a tabela a seguir:

|SALÁRIO LÍQUIDO|GRATIFICAÇÃO|
|---|---|
|Até 350,00| 100,00|
|Superior a  350| 50,00|

  * O salário a receber do funcionário é igual ao salário líquido mais a gratificação.

  ```code
  LEIA salario_minimo, numero_horas_trabalhadas, numero_dependentes, numero_horas_extras
  
  valor_hora = 1/5 * salario_minimo
  salario_mes = numero_horas_trabalhadas * valor_hora
  valor_dependentes = 32 * numero_dependentes
  valor_hora_extra = numero_horas_extras * (valor_hora + (valor_hora * 50/100))
  salario_bruto =salario_mes + valor_dependentes + valor_hora_extra
  
  SE salario_bruto < 200
        imposto = 0
  SENÃO SE salario_bruto >= 200 E salario_bruto <= 500
        imposto = salario_bruto * 10/100
  SENÃO SE salario_bruto > 500
        imposto = salario_bruto * 20/100
  salario_liquido = salario_bruto – imposto
  SE salario_liquido <= 350
        gratificacao = 100
  SENÃO
        gratificacao = 50
  salario_a_receber = salario_liquido + gratificacao
  
  ESCREVA salario_a_receber
  ```
"""

# Digite seu código aqui

"""### 27 Um supermercado deseja reajustar os preços de seus produtos usando o seguinte critério: o produto poderá ter seu preço aumentado ou diminuído. Para o preço ser alterado, o produto deve preencher pelo menos um dos requisitos a seguir:

|VENDA MÉDIA MENSAL|PREÇO ATUAL|% DE AUMENTO|% DE DIMINUIÇÃO|
|---|--|---|---|
|< 500|<  30000|10|-|
|\>= 500 e <1200|\>=  30.00 e <  80.00|15|-|
|\>= 1200|\>=  80.00|-|20|

* Faça um programa que receba o preço atual e a venda média mensal do produto, calcule e mostre o novo preço.

```code
LEIA preco_atual, media_mensal_vendas

SE media_mensal_vendas < 500 OU preco_atual < 30
    novo_preco = preco_atual + 10/100 * preco_atual
SENÃO SE media_mensal_vendas >= 500 E media_mensal_vendas < 1200 OU preco_atual >= 30 E preco_atual<80
    novo_preco = preco_atual + 15 / 100 * preco_atual
SENÃO SE venda >= 1200 OU preco_atual >= 80
    novo_preco = preco_atual – 20 / 100 * preco_atual
      
ESCREVA novo_preco
```
"""

# Digite seu código aqui

"""### 28. Faça um programa para resolver equações do 2 o grau.

**ax² + bx + c = 0**

A variável *a* deve ser diferente de zero*

  * delta = b ** 2 - 4 * a * c
  * delta < 0.  **Não existe raiz real**
  * delta = 0. **Existe uma raiz real**
    * x = (-b) / (2 * a)
  * delta > 0. **Existem duas raízes reais**
    * x1 = -b + raiz(delta)/ (2 * a)
    * x2 = -b  - raiz(delta)/ (2 * a)

```code
LEIA a, b, c
SE a = 0
    ESCREVA “Estes valores não formam uma equação de segundo grau”
SENÃO
    delta = (b * b) – ( 4 * a * c)
    SE delta < 0
        ESCREVA “Não existe raiz real”
    SE delta = 0
        ESCREVA “Existe uma raiz real”
        x1 = (– b) / (2 * a)
        ESCREVA x1
    SE delta > 0
        ESCREVA “Existem duas raízes reais”
        x1 = (– b) + raiz(delta) / (2 * a)
        x2 = (– b) - raiz(delta) / (2 * a)
        ESCREVA(x1, x2)
```
"""

# Digite seu código aqui

"""### 29. Dados três valores X, Y e Z, verifique se eles podem ser os comprimentos dos lados de um triângulo e, se forem, verifique se é um triângulo equilátero, isósceles ou escaleno. Se eles não formarem um triângulo, escreva uma mensagem.
Considere que:
* o comprimento de cada lado de um triângulo é menor que a soma dos outros dois lados;
* chama-se equilátero o triângulo que tem três lados iguais;
* denomina-se isósceles o triângulo que tem o comprimento de dois lados iguais;
* recebe o nome de escaleno o triângulo que tem os três lados diferentes.

```code
LEIA x, y, z
SE x < y + z E y < x + z E z < x + y
    SE x = y E y = z
        ESCREVA “Triângulo Equilátero”
    SENÃO SE x = y OU x = z OU y = z
        ESCREVA “Triângulo Isósceles”
    SENÃO SE x ≠ y E x ≠ z E y ≠ z
        ESCREVA “Triângulo Escaleno”
SENÃO
    ESCREVA “Essas medidas não formam um triângulo”
```
"""

# Digite seu código aqui

"""### 30. Faça um programa que receba a altura e peso de uma pessoa. De acordo com a tabela a seguir, verifique e mostre a classificação dessa pessoa.

|ALTURA|ATÉ 60|ENTRE 60 E 90 (INCLUSIVE)|ACIMA DE 90|
|---|---|---|---|
|Menores que 1,20|A|D|G|
|De 1,20 a 1,70|B|E|H|
|Maiores que 1,70|C|F|I|

```code
LEIA altura, peso
SE altura < 1.20
    SE peso <= 60
        ESCREVA “A”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “D”
    SENÃO SE peso > 90
        ESCREVA “G”
SENÃO SE altura >= 1.20 E altura <= 1.70
    SE peso <= 60
        ESCREVA “B”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “E”
    SENÃO SE peso > 90
        ESCREVA “H”
SENÃO SE altura > 1.70
    SE peso <= 60
        ESCREVA “C”
    SENÃO SE peso > 60 E peso <= 90
        EESCREVA “F”
    SENÃO SE peso > 90
        ESCREVA “I”
```
"""

# Digite seu código aqui

"""### 31. Faça um programa que receba:

* O código de um produto comprado, supondo que a digitação do código do produto seja sempre válida, isto é, um número * inteiro entre 1 e 10.
* O peso do produto em quilos.
* O código do país de origem, supondo que a digitação do  código seja sempre válida, isto é, um número inteiro entre 1 e 3.

|CÓDIGO DO PAÍS DE ORIGEM|IMPOSTO|
|---|---|
|1|0%|
|2|15%|
|3|25%|

|CÓDIGO DO PAÍS DO PRODUTO|PREÇO POR GRAMA|
|---|---|
|1 a 4|10|
|5 a 7|25|
|8 a 10|35|

Calcule e mostre:
* o peso do produto convertido em gramas;
* o preço total do produto comprado;
* valor do imposto, sabendo que ele é cobrado sobre o * preço total do produto comprado e dependendo país de origem;
* o valor total, preço total do produto mais imposto.

```code
LEIA codigo_produto, peso_quilos, codigo_pais
peso_em_gramas = peso_quilos * 1000
ESCREVA peso_em_gramas
SE codigo_produto >= 1 E codigo_produto <= 4
   preco_por_grama = 10
SENÃO SE codigo_produto >= 5 E codigo_produto <= 7
   preco_por_grama = 25
SENÃO SE codigo_produto >= 8 E codigo_produto <= 10
   preco_por_grama = 35    
preco_total = peso_em_gramas *preco_por_grama
ESCREVA preco_total
SE codigo_pais = 1
    imposto = 0
SENÃO SE codigo_pais = 2
    imposto = preco_total * 15/100
SENÃO SE codigo_pais = 3
    imposto = preco_total * 25/100    
ESCREVA imposto
valor_total = preco_total + imposto
ESCREVA valor_total
```
"""

# Digite seu código aqui

"""### 32. Faça um programa que receba:
* o código do estado de origem da carga de um caminhão, supondo que a digitação do código do estado seja sempre válida, isto é, um número inteiro entre 1 e 5;
* o peso da carga do caminhão em toneladas;
* o código da carga, supondo que a digitação do código seja sempre válida, isto é, um número inteiro entre 10 e 40.

| CÓDIGO DO ESTADO| IMPOSTO|
|---|---|
|1|35%|
|2|25%|
|3|15%|
|4|5%|
|5|Isento|
>
CÓDIGO DA CARGA|PREÇO POR QUILO
---|---
10 a 20|100
21 a 30|250
31 a 40|400

Calcule e mostre:
* o peso da carga do caminhão convertido em quilos;
* o preço da carga do caminhão;
* o valor do imposto, sabendo que o imposto é cobrado sobre o preço da carga do caminhão e depende do estado de origem;
* o valor total transportado pelo caminhão, preço da carga mais imposto.

```
LEIA codigo_estado, peso_em_toneladas, codigo_carga
peso_em_quilos = peso_em_toneladas * 1000
ESCREVA peso_em_quilos
SE codigo_carga >= 10 E codigo_carga <= 20
    preco_da_carga = 100 * peso_em_quilos
SENÃO SE codigo_carga >= 21 E codigo_carga <= 30
    preco_da_carga = 250 * peso_em_quilos
SENÃO SE codigo_carga >= 31 E codigo_carga <= 40
    preco_da_carga = 340 * peso_em_quilos   
ESCREVA preco_da_carga
SE codigo_estado = 1
    imposto = 35/100 * preco_da_carga
SENÃO SE codigo_estado = 2
    imposto = 25/100 * preco_da_carga
SENÃO SE codigo_estado = 3
    imposto = 15/100 * preco_ds_carga
SENÃO SE codigo_estado = 4
    imposto = 5/100 * preco_da_carga
SENÃO SE codigo_estado = 5
    imposto = 0
ESCREVA imposto
valor_total = preco_da_carga + imposto
ESCREVA valor_total
```
"""

# Digite seu código aqui

"""### 33. Faça um programa que receba o salário base e o tempo de serviço de um funcionário. Calcule e mostre:
* O imposto, conforme a tabela a seguir.

|SALÁRIO BASE|% SOBRE O SALÁRIO BASE|
|---|---|
|< 200|isento|
|>= 250 E <= 450|3%|
|>  450 E < 700|8%|
|>=  700|12%|

* A gratificação, de acordo com a tabela a seguir.

SALÁRIO BASE R$|TEMPO DE SERVIÇO|GRATIFICAÇÃO
---|---|---
Superior a 500,00|Até 3 anos|20
 | Mais de 3 anos|30
  --------------------------|---------|--------------
Até 500,00|Até 3 anos|23
|Entre 3 e 6 anos|35
|Acima de 6 anos|33

* O salário líquido, ou seja, salário base menos imposto mais gratificação.
* A categoria, que está na tabela a seguir.

```
LEIA salario_base, tempo

SE salario_base < 200
    imposto = 0
SENÃO SE salario_base <= 450
    imposto = 3/100 * salario_base
SENÃO SE sal_base < 700
    imposto = 8/100 * salario_base
SENÃO
    imposto = 12/100 * salario_base
ESCREVA imposto
SE salario_base > 500
    SE tempo <= 3
         gratificacao = 20
    SENÃO
        gratificacao = 30
SENÃO
    SE tempo <= 3
        gratificacao = 23
    SENÃO SE tempo < 6
        gratificacao = 35
    SENÃO gratificacao = 33
ESCREVA gratificacao
salario_liquido = salario_base – imposto + gratificacao
ESCREVA salario_liqquido
SE salario_liquido <= 350
    ESCREVA “Classificação A”
SENÃO SE salario_liqquido < 600
    ESCREVA “Classificação B”
SENÃO
    ESCREVA “Classificação C”
```
"""

# Digite seu código aqui

"""### 34. Faça um programa que:
* receba o valor do salário mínimo,
* o turno de trabalho (M — matutino; V — vespertino; ou N — noturno),
* a categoria (O — operário; G — gerente)
* número de horas trabalhadas no mês de um funcionário.

*Suponha a digitação apenas de dados válidos e, quando houver digitação de letras, utilize maiúsculas.*

**Calcule e mostre:**

* O coeficiente do salário, de acordo com a tabela a seguir.

TURNO DE TRABALHO|VALOR DO COEFICIENTE
---|---
M - Matutino|10% do salário mínimo
V - Vespertino|15% do salário mínimo
N - Noturno|20% do salário mínimo

* O valor do salário bruto, ou seja, o número de horas trabalhadas multiplicado pelo valor do coeficiente do salário.

* O imposto, de acordo com a tabela a seguir.

CATEGORIA| SALÁRIO BRUTO|IMPOSTO SOBRE O SALÁRIO BRUTO
---|---|---
O - Operário|>= 300,00|5%
O - Operário|< 300,00|3%
G - Gerente|>= 300,00|6%
G - Gerente|< 300,00|4%

* A gratificação, de acordo com as regras a seguir. Se o funcionário preencher todos os requisitos a seguir, sua gratificação será de 50,00; caso contrário, será de 30,00. Os requisitos são:
 * Turno: Noturno
  * Número de horas trabalhadas: Superior a 80 horas
  * O auxílio alimentação, de acordo com as seguintes regras.
* Auxilio alimentação, um terço do seu salário bruto; caso contrário, será de metade do seu salário bruto. Os requisitos são:
  * Se o funcionário preencher algum dos requisitos a seguir, seu auxílio alimentação será de
  * Categoria: Operário
  * Coeficiente do salário: < = 25
* O salário líquido, ou seja, salário bruto menos imposto mais gratificação mais auxílio alimentação.
* A classificação, de acordo com a tabela a seguir:

SALÁRIO LÍQUIDO|MENSAGEM
---|---
Menor que 350,00|Mal remunerado
Entre 350 e 600,00|Normal
Maior que 600,00|Bem remunerado

```
LEIA salario_minino, turno, categoria, numero_de_horas_trabalhadas
SE turno = “M”
     coeficiente = 10/100 * salario_minino
SENÃO SE turno = “V”
     coeficiente = 15/100 * salario_minino
SENÃO SE turno = “N”
     coeficiente = 12/100 * salario_minino
     
ESCREVA coeficiente

salario_bruto = numero_de_horas_trabalhadas * coeficiente

ESCREVA salario_bruto

SE categoria = “O”
    SE sal_bruto >= 300
        imposto = 5/100 * sal_bruto
    SENÃO
        imposto = 3/100 * sal_bruto
SENÃO
    SE salario_bruto >= 400
        imposto = 6/100 * salario_bruto
    SENÃO
         imposto = 4/100 * salario_bruto
         
ESCREVA imposto

SE turno = “N” E numero_de_horas_trabalhadas > 80
    gratificacao = 50
SENÃO
    gratificacao = 30
    
ESCREVA gratificacao

SE categoria = “O” OU coeficiente <= 25
    auxilio = 1/3 * salario_bruto
SENÃO
    auxilio = 1/2 * salario_bruto
    
ESCREVA auxilio

salario_liquido = salario_bruto – imposto + gratificacao + auxilio

ESCREVA salario_liquido

SE salario_liquido < 350
     ESCREVA “Mal Remunerado”
SENÃO SE salario_liquido >= 350 E salario_liqquido <= 600
     ESCREVA “Normal”
SENÃO SE salario_liquido > 600
     ESCREVA “Bem Remunerado”
```
"""

# Digite seu código aqui

"""### 35. Faça um programa que receba de um produto:
* o preço
* o tipo (A — alimentação; L — limpeza; e V — vestuário)
* a refrigeração (S — produto que necessita de refrigeração; e N — produto que não necessita de refrigeração) .

**Suponha que haverá apenas a digitação de dados válidos e, quando houver digitação de letras, utilize maiúsculas. Calcule e mostre:**

* O valor adicional, de acordo com a tabela a seguir:

REFRIGERAÇÃO|TIPO|PREÇO|VALOR ADICIONAL
---|---|---|---
N|A|<  15,00|2,00|
 | |>= 15,00|5,00|
 |---------|--------------|-------------------------------
 |L|< 10,00|1,50
 | |>= 10,00|2,50
  |---------|--------------|-------------------------------
 |V|< 30,00|3,00
 ||>= 30,00|2,50
  --------------------------|---------|--------------|-------------------------------
S|A||8,00
|L||0,00
|V||0,00

* O valor do imposto, de acordo com a regra a seguir.

PREÇO|PERCENTUAL SOBRE O PREÇO
---|---
< 25,00|5%
>= 25,00|8%

O preço de custo, ou seja, preço mais imposto.
O desconto, de acordo com a regra a seguir.

O produto que não preencher nenhum dos requisitos a seguir terá desconto de 3%, caso contrário, 0 (zero). Os requisitos são:
* Tipo: A
* Refrigeração: S

* O novo preço, ou seja, preço de custo mais adicional menos desconto.
* A classificação, de acordo com a regra a seguir.

NOVO PREÇO|CLASSIFICAÇÃO
---|---
<= 50,00|Barato
Entre 50,01 e 100,00|Normal
>= 100,00|Caro


```
LEIA pre, tipo, refrig
SE refrig = “N”
    SE tipo = “A”
        SE pre < 15
           valor_adic = 2
        SENÃO
           valor_adic = 5
    SE tipo = “L”
        SE pre < 10
           valor_adic = 1.5
        SENÃO
           valor_adic = 2.5
    SE tipo = “V”
        SE pre < 30
           valor_adic = 3
        SENÃO
           valor_adic = 2.5
SENÃO SE tipo = “A”
    valor_adic = 8
    SE tipo = “L”
        valor_adic = 0
    SE tipo = “V”
        valor_adic = 0
ESCREVA valor_adic
SE pre < 25
    imposto = 5/100 * pré
SENÃO
    imposto = 8/100 * pre
ESCREVA imposto
pre_custo = pre + imposto
ESCREVA pre_custo
SE tipo != “A” E refrig != “S”
  desconto = 3/100 * pre_custo
SENÃO
  desconto = 0
ESCREVA desconto
novo_pre = pre_custo + valor_adic – desconto
ESCREVA novo_pre
SE novo_pre <= 50
    ESCREVA “Barato”
SENÃO SE novo_pre < 100
    ESCREVA “Normal”
SENÃO
    ESCREVA “Caro”

"""

# Digite seu código aqui

"""### 36. Faça um programa que receba a medida de um ângulo em graus. Calcule e mostre o quadrante em que se localiza esse ângulo. Considere os quadrantes da trigonometria e, para ângulos maiores que 360° ou menores que −360°, reduzí-los, mostrando também o número de voltas e o sentido da volta (horário ou anti-horário).
```
SE angulo > 360 OU angulo < -360
    voltas = parte inteira(angulo / 360)    
    angulo = RESTO(angulo / 360)
SENÃO
    voltas = 0
SE angulo = 0 OU angulo = 90 OU angulo = 180
           OU angulo = 270 OU angulo = 360
           OU angulo = -90 OU angulo = -180
           OU angulo = -270 OU angulo = -360
  ESCREVA “Está em cima de algum dos eixos”
  SE (angulo > 0 E angulo < 90) OU (angulo < -270 E angulo > -360)
    ESCREVA “1o Quadrante”
  SENÃO SE (angulo > 90 E angulo < 180) OU (angulo < -180 E angulo > -270)
    ESCREVA “2o Quadrante”
  SENÃO SE (angulo > 180 E angulo < 270) OU (angulo < -90 E angulo > -180)
    ESCREVA “3o Quadrante”
  SENÃO SE (angulo > 270 E angulo < 360) OU (angulo < 0 E angulo > -90)
    ESCREVA “4o Quadrante”
  ESCREVA voltas, “ volta(s) no sentido “
SE angulo < 0
    ESCREVA “horário”
SENÃO
    ESCREVA “anti-horário”
```
"""

# Digite seu código aqui